### ISSUE TITLE
segfault in recv_function_raw

### ISSUE THREAD

**Issue by falkevik** [sctplab/usrsctp#182]
In commit ea1d1d97 `ncounter` was changed from `signed` to `unsigned int` which can lead to segfault.
Should we have signed int or change to `ncounter -= min(ncounter, iovlen);` in below code snippet?

```
do {
    recvmbuf[i]->m_next = recvmbuf[i+1];
    SCTP_BUF_LEN(recvmbuf[i]->m_next) = min(ncounter, iovlen);
    i++;
    ncounter -= iovlen;
    (to_fill)++;
} while (ncounter > 0);
```

```
[Switching to Thread 0x7fe41b7fe700 (LWP 7244)]
0x00007fe438786c63 in recv_function_raw (arg=0x0) at user_recv_thread.c:368
368					SCTP_BUF_LEN(recvmbuf[i]->m_next) = min(ncounter, iovlen);
(gdb) bt
#0  0x00007fe438786c63 in recv_function_raw (arg=0x0) at user_recv_thread.c:368
#1  0x00007fe47bcfc7fc in start_thread (arg=0x7fe41b7fe700) at pthread_create.c:465
#2  0x00007fe47b821b0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) p n
$1 = 2448
(gdb) p ncounter
$2 = 4294904208

```

**Comment by tuexen** [comment]
Fixed in https://github.com/sctplab/usrsctp/commit/2fa27be70a7a2a19ca64ec65e6fcb8e6258bccef.
Thanks for reporting.
