### ISSUE TITLE
Crash in sctp_indata.c

### ISSUE THREAD

**Issue by sancane** [sctplab/usrsctp#266]
Stack trace:
#1 0x00007fc044b57b1d in sctp_handle_old_unordered_data (stcb=0x7fbf8805d550, asoc=0x7fbf8805d5a8, strm=0x7fc0481ba4c0, control=0xffffffffffffffff, pd_point=65536, inp_read_lock_held=0) at netinet/sctp_indata.c:826
#2 0x00007fc044b58c04 in sctp_deliver_reasm_check (stcb=0x7fbf8805d550, asoc=0x7fbf8805d5a8, strm=0x7fc0481ba4c0, inp_read_lock_held=0) at netinet/sctp_indata.c:1096
#3 0x00007fc044b5cd02 in sctp_process_a_data_chunk (stcb=0x7fbf8805d550, asoc=0x7fbf8805d5a8, m=0x7fbe4dfe24b8, offset=12, chk_length=1188, net=0x7fbf88082c40, high_tsn=0x7fbe4dfe23f0, abort_flag=0x7fbe4dfe2228, break_flag=0x7fbe4dfe222c, last_chunk=1, chk_type=0 '\000') at netinet/sctp_indata.c:2302
#4 0x00007fc044b5dee6 in sctp_process_data (mm=0x7fbe4dfe24b8, iphlen=0, offset=0x7fbe4dfe2340, length=1200, inp=0x7fc048011fb0, stcb=0x7fbf8805d550, net=0x7fbf88082c40, high_tsn=0x7fbe4dfe23f0) at netinet/sctp_indata.c:2769
#5 0x00007fc044b75ae5 in sctp_common_input_processing (mm=0x7fbe4dfe24b8, iphlen=0, offset=12, length=1200, src=0x7fbe4dfe24d0, dst=0x7fbe4dfe24c0, sh=0x7fc0481dbe50, ch=0x7fc0481dbe5c, compute_crc=1 '\001', ecn_bits=0 '\000', vrf_id=0, port=0) at netinet/sctp_input.c:6049
#6 0x00007fc044b43d04 in usrsctp_conninput (addr=0x7fbfc0073720, buffer=0x7fc04819f2c0, length=1200, ecn_bits=0 '\000') at user_socket.c:3492

usrcp source cloned from this commit: https://github.com/sctplab/usrsctp/commit/35c1d97020a20014b989bba4f20225fd9429c4f4

This happening using sctp with WebRTCData channels. Unfortunatelly I can not provide more info about the channel configuration.

**Comment by tuexen** [comment]
Which platform is this on? Any way I could reproduce it?

**Comment by sancane** [comment]
It's Linux Centos, Unfortunatelyt I am unable to reproduce it. This is a trace I got from a server I have in prod, in fact this is the first time I've seen sctp crash this way.

**Comment by tuexen** [comment]
Yeah, it looks strage... Normally is pointer is NULL instead of not being NULL. Here it is (void *)-1...
No idea how this could happen...
