### ISSUE TITLE
Memory leak detected during fuzzing

### ISSUE THREAD

**Issue by markwo** [sctplab/usrsctp#355]
I confirmed this leak repros with the current code in master.

LeakSanitizer detected a leak during fuzzing. I've included a PCAP of the fuzzed messages as well as the text packet dump. The repro is actually a stand-alone test app (doesn't require a fuzzed testcase input file), so I'll see if I can simplify it down to a single .c file you can use to repro locally.

[packets.txt](https://github.com/sctplab/usrsctp/files/3531833/packets.txt)
[pcap.zip](https://github.com/sctplab/usrsctp/files/3531835/pcap.zip)

```
==15286==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 152 byte(s) in 1 object(s) allocated from:
    #0 0x5605bc74023d in malloc third_party/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x5605bc836daa in sctp_send_sack third_party/usrsctp/usrsctplib/netinet/sctp_output.c:11118:3
    #2 0x5605bc8939bd in sctp_process_data third_party/usrsctp/usrsctplib/netinet/sctp_indata.c:2935:2
    #3 0x5605bc7df098 in sctp_common_input_processing third_party/usrsctp/usrsctplib/netinet/sctp_input.c:6069:12
    #4 0x5605bc778f47 in usrsctp_conninput third_party/usrsctp/usrsctplib/user_socket.c:3518:2
    #5 0x5605bc7659da in usrsctp_fuzzer::SctpSocket::SctpSocket()::$_0::operator()(std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> >) const third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:155:46
    #6 0x5605bc7658a1 in decltype(std::__u::forward<usrsctp_fuzzer::SctpSocket::SctpSocket()::$_0&>(fp)(std::__u::forward<std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> > >(fp0))) std::__u::__invoke<usrsctp_fuzzer::SctpSocket::SctpSocket()::$_0&, std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> > >(usrsctp_fuzzer::SctpSocket::SctpSocket()::$_0&, std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> >&&) third_party/crosstool/v18/stable/toolchain/bin/../include/c++/v1/type_traits:3530:1
    #7 0x5605bc75a420 in usrsctp_fuzzer::MessageSocket::ReceiveData(std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> >) third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:107:5
    #8 0x5605bc767e11 in usrsctp_fuzzer::SctpFuzzer::SetUp()::$_2::operator()(std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> >) const third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:413:19
    #9 0x5605bc767c41 in decltype(std::__u::forward<usrsctp_fuzzer::SctpFuzzer::SetUp()::$_2&>(fp)(std::__u::forward<std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> > >(fp0))) std::__u::__invoke<usrsctp_fuzzer::SctpFuzzer::SetUp()::$_2&, std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> > >(usrsctp_fuzzer::SctpFuzzer::SetUp()::$_2&, std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> >&&) third_party/crosstool/v18/stable/toolchain/bin/../include/c++/v1/type_traits:3530:1
    #10 0x5605bc75a7fe in usrsctp_fuzzer::MessageSocket::ProcessNextWriteInQueue() third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:122:3
    #11 0x5605bc75cbec in usrsctp_fuzzer::SctpFuzzer::PumpMessages() third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:722:22
    #12 0x5605bc75e7e9 in LLVMFuzzerTestOneInput third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:775:8
    #13 0x5605bc92b926 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:554:15
    #14 0x5605bc915a39 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:292:6
    #15 0x5605bc91ac7e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:775:9
    #16 0x5605bc934482 in main third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #17 0x7fd24cea4bbc in __libc_start_main (/usr/grte/v4/lib64/libc.so.6+0x38bbc)
    #18 0x5605bc6a8768 in _start /usr/grte/v4/debug-src/src/csu/../sysdeps/x86_64/start.S:108

Indirect leak of 632 byte(s) in 1 object(s) allocated from:
    #0 0x5605bc74023d in malloc third_party/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x5605bc79af7e in sctp_add_remote_addr third_party/usrsctp/usrsctplib/netinet/sctp_pcb.c:4517:8
    #2 0x5605bc79d913 in sctp_aloc_assoc third_party/usrsctp/usrsctplib/netinet/sctp_pcb.c:5143:13
    #3 0x5605bc901f08 in sctpconn_connect third_party/usrsctp/usrsctplib/netinet/sctp_usrreq.c:8166:9
    #4 0x5605bc77394f in user_connect third_party/usrsctp/usrsctplib/user_socket.c:2101:10
    #5 0x5605bc773d4c in usrsctp_connect third_party/usrsctp/usrsctplib/user_socket.c:2158:10
    #6 0x5605bc75b721 in usrsctp_fuzzer::SctpSocket::ConnectSctpSocket(socket*, usrsctp_fuzzer::SctpSocket*) third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:259:24
    #7 0x5605bc75af40 in usrsctp_fuzzer::SctpSocket::Start() third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:182:8
    #8 0x5605bc75c9af in usrsctp_fuzzer::SctpFuzzer::StartSockets() third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:505:17
    #9 0x5605bc75e76a in LLVMFuzzerTestOneInput third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:751:8
    #10 0x5605bc92b926 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:554:15
    #11 0x5605bc915a39 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:292:6
    #12 0x5605bc91ac7e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:775:9
    #13 0x5605bc934482 in main third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #14 0x7fd24cea4bbc in __libc_start_main (/usr/grte/v4/lib64/libc.so.6+0x38bbc)
    #15 0x5605bc6a8768 in _start /usr/grte/v4/debug-src/src/csu/../sysdeps/x86_64/start.S:108

Indirect leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x5605bc74023d in malloc third_party/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x5605bc7ac8f0 in m_get third_party/usrsctp/usrsctplib/user_mbuf.c:125:9
    #2 0x5605bc7b0be8 in m_copym third_party/usrsctp/usrsctplib/user_mbuf.c:1176:4
    #3 0x5605bc89643b in sctp_process_a_data_chunk third_party/usrsctp/usrsctplib/netinet/sctp_indata.c
    #4 0x5605bc8931b3 in sctp_process_data third_party/usrsctp/usrsctplib/netinet/sctp_indata.c:2785:8
    #5 0x5605bc7df098 in sctp_common_input_processing third_party/usrsctp/usrsctplib/netinet/sctp_input.c:6069:12
    #6 0x5605bc778f47 in usrsctp_conninput third_party/usrsctp/usrsctplib/user_socket.c:3518:2
    #7 0x5605bc7659da in usrsctp_fuzzer::SctpSocket::SctpSocket()::$_0::operator()(std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> >) const third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:155:46
    #8 0x5605bc7658a1 in decltype(std::__u::forward<usrsctp_fuzzer::SctpSocket::SctpSocket()::$_0&>(fp)(std::__u::forward<std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> > >(fp0))) std::__u::__invoke<usrsctp_fuzzer::SctpSocket::SctpSocket()::$_0&, std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> > >(usrsctp_fuzzer::SctpSocket::SctpSocket()::$_0&, std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> >&&) third_party/crosstool/v18/stable/toolchain/bin/../include/c++/v1/type_traits:3530:1
    #9 0x5605bc75a420 in usrsctp_fuzzer::MessageSocket::ReceiveData(std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> >) third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:107:5
    #10 0x5605bc767e11 in usrsctp_fuzzer::SctpFuzzer::SetUp()::$_2::operator()(std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> >) const third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:413:19
    #11 0x5605bc767c41 in decltype(std::__u::forward<usrsctp_fuzzer::SctpFuzzer::SetUp()::$_2&>(fp)(std::__u::forward<std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> > >(fp0))) std::__u::__invoke<usrsctp_fuzzer::SctpFuzzer::SetUp()::$_2&, std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> > >(usrsctp_fuzzer::SctpFuzzer::SetUp()::$_2&, std::__u::unique_ptr<usrsctp_fuzzer::RawBuffer, std::__u::default_delete<usrsctp_fuzzer::RawBuffer> >&&) third_party/crosstool/v18/stable/toolchain/bin/../include/c++/v1/type_traits:3530:1
    #12 0x5605bc75a7fe in usrsctp_fuzzer::MessageSocket::ProcessNextWriteInQueue() third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:122:3
    #13 0x5605bc75cbec in usrsctp_fuzzer::SctpFuzzer::PumpMessages() third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:722:22
    #14 0x5605bc75e7e9 in LLVMFuzzerTestOneInput third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:775:8
    #15 0x5605bc92b926 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:554:15
    #16 0x5605bc915a39 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:292:6
    #17 0x5605bc91ac7e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:775:9
    #18 0x5605bc934482 in main third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #19 0x7fd24cea4bbc in __libc_start_main (/usr/grte/v4/lib64/libc.so.6+0x38bbc)
    #20 0x5605bc6a8768 in _start /usr/grte/v4/debug-src/src/csu/../sysdeps/x86_64/start.S:108

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x5605bc74023d in malloc third_party/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x5605bc79ccea in sctp_userspace_rtalloc third_party/usrsctp/usrsctplib/netinet/sctp_os_userspace.h:857:33
    #2 0x5605bc79b5e7 in sctp_add_remote_addr third_party/usrsctp/usrsctplib/netinet/sctp_pcb.c:4631:2
    #3 0x5605bc79d913 in sctp_aloc_assoc third_party/usrsctp/usrsctplib/netinet/sctp_pcb.c:5143:13
    #4 0x5605bc901f08 in sctpconn_connect third_party/usrsctp/usrsctplib/netinet/sctp_usrreq.c:8166:9
    #5 0x5605bc77394f in user_connect third_party/usrsctp/usrsctplib/user_socket.c:2101:10
    #6 0x5605bc773d4c in usrsctp_connect third_party/usrsctp/usrsctplib/user_socket.c:2158:10
    #7 0x5605bc75b721 in usrsctp_fuzzer::SctpSocket::ConnectSctpSocket(socket*, usrsctp_fuzzer::SctpSocket*) third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:259:24
    #8 0x5605bc75af40 in usrsctp_fuzzer::SctpSocket::Start() third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:182:8
    #9 0x5605bc75c9af in usrsctp_fuzzer::SctpFuzzer::StartSockets() third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:505:17
    #10 0x5605bc75e76a in LLVMFuzzerTestOneInput third_party/usrsctp/fuzzer/usrsctp_fuzzer.cc:751:8
    #11 0x5605bc92b926 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:554:15
    #12 0x5605bc915a39 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:292:6
    #13 0x5605bc91ac7e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:775:9
    #14 0x5605bc934482 in main third_party/llvm/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #15 0x7fd24cea4bbc in __libc_start_main (/usr/grte/v4/lib64/libc.so.6+0x38bbc)
    #16 0x5605bc6a8768 in _start /usr/grte/v4/debug-src/src/csu/../sysdeps/x86_64/start.S:108

SUMMARY: AddressSanitizer: 1080 byte(s) leaked in 4 allocation(s).
```

**Comment by markwo** [comment]
With some help from @weinrank I got a repro based on his fuzzer_connected.c code working. See the attached source. You need to run this with a dummy input testcase (contents are ignored). e.g. 
`./fuzzer_connected CORPUS_CONNECTED/tsctp-000000 -detect_leaks=1`

[fuzzer_connected.zip](https://github.com/sctplab/usrsctp/files/3553279/fuzzer_connected.zip)

**Comment by tuexen** [comment]
@markwo Just to be sure: this problem occurs with the master branch, right?

**Comment by markwo** [comment]
Correct - repro'd against master as of today.

**Comment by tuexen** [comment]
Great. Thanks for the clarification.

**Comment by tuexen** [comment]
The issue can be reproduced using the following packetdrill script:
```
+0.0 socket(..., SOCK_STREAM, IPPROTO_SCTP) = 3
+0.0 fcntl(3, F_GETFL) = 0x2 (flags O_RDWR)
+0.0 fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK) = 0

+0.1 connect(3, ..., ...) = -1 EINPROGRESS (Operation now in progress)
+0.0 > sctp: INIT[flgs=0, tag=1, a_rwnd=..., os=..., is=..., tsn=0, ...]
+0.0 < sctp: INIT_ACK[flgs=0, tag=2, a_rwnd=1500, os=1, is=1, tsn=1, STATE_COOKIE[len=4, val=...]]
+0.0 > sctp: COOKIE_ECHO[flgs=0, len=4, val=...]
+0.0 < sctp: COOKIE_ACK[flgs=0]

+0.0 < sctp: DATA[flgs=0, len=32, tsn=3072, sid=0, ssn=0, ppid=0]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[3072:3072], dups=[]]
+0.0 < sctp: DATA[flgs=B, len=32, tsn=1024, sid=0, ssn=0, ppid=0]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[1024:1024, 3072:3072], dups=[]]
+0.0 < sctp: DATA[flgs=E, len=32, tsn=1025, sid=0, ssn=0, ppid=0]
+0.0 > sctp: SACK[flgs=0, cum_tsn=0, a_rwnd=..., gaps=[1024:1025, 3072:3072], dups=[]]

+0.0 recv(3, ..., 1024, 0) = 32
```

**Comment by tuexen** [comment]
@markwo https://github.com/sctplab/usrsctp/commit/4687803d5021b7f452438bc8acc8201294265e74 should fix this issue. Can you retest and confirm?

**Comment by markwo** [comment]
I can confirm this fixes the issue, thanks!
