### ISSUE TITLE
runtime error: signed integer overflow: 1955827320 + 723124158 cannot be represented in type 'int'

### ISSUE THREAD

**Issue by weinrank** [sctplab/usrsctp#375]
```
➜  fuzzer git:(fuzzer-connected) ✗ ./fuzzer_connect_multi ./CORPUS_CONNECT/crash-0a63175dc6b51474dc08197431ec36d11db5e77b
INFO: Seed: 1912993788
INFO: Loaded 1 modules   (37952 inline 8-bit counters): 37952 [0x10a9f1280, 0x10a9fa6c0),
INFO: Loaded 1 PC tables (37952 PCs): 37952 [0x10a9fa6c0,0x10aa8eac0),
./fuzzer_connect_multi: Running 1 inputs 1 time(s) each.
Running: ./CORPUS_CONNECT/crash-0a63175dc6b51474dc08197431ec36d11db5e77b
[0.000] >>>>>>>>>>>>>>>>>>> LLVMFuzzerTestOneInput() - Stage 4
[0.002] [0.002] vrf_id 0x0: adding address: AF_CONN address: 0x1
[0.002] usrsctp initialized
[0.003] SCTP: add HMAC id 1 to list
[0.003] SCTP: added chunk 193 (0xc1) to Auth list
[0.003] SCTP: added chunk 128 (0x80) to Auth list
[0.003] Bind called port: 5000
[0.003] [0.003] Addr: IPv4 address: 0.0.0.0:5000
[0.003] Main hash to bind at head:0x625000000198, bound port:5000 - in tcp_pool=0
[0.003] [0.003] Allocate an association for peer:AF_CONN address: 0x1
[0.003] Port:5001
[0.003] [0.003] Adding an address (from:1) to the peer: AF_CONN address: 0x1
[0.004] Association 0x61d000001480 now allocated
[0.004] Sending INIT
[0.004] Sending INIT - calls lowlevel_output
[0.004] length 104 / sizeof 12
[0.004] Found INIT, extracting VTAG : 2502642693

O 13:50:37.284605 0000 13 88 13 89 00 00 00 00 00 00 00 00 01 00 00 5a 05 4c 2b 95 00 02 00 00 00 0a 08 00 3c db 41 bc 80 00 00 04 c0 00 00 04 80 08 00 0b c0 c2 0f c1 80 82 40 00 80 02 00 24 08 c2 80 d5 2d 1d f4 09 54 ed 5a 53 9d fe f9 72 95 e8 b1 44 e5 ad 8d 00 3b 65 a0 3b 5b 1d 48 cd 80 04 00 06 00 01 00 00 80 03 00 06 80 c1 00 00 # SCTP_PACKET

I 13:50:37.285685 0000 13 89 13 88 05 4c 2b 95 00 00 00 00 02 00 01 f8 c7 a1 b0 4d 00 1c 71 c7 00 0a ff ff 03 91 94 1b 80 00 00 04 c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 61 6c 7e 52 2a db e0 a2 aa 78 25 1e 12 c5 01 9e 4c 60 16 df 01 6d a1 d5 cd be a7 5d a2 73 f4 1b 80 04 00 08 00 03 00 01 80 03 00 07 00 80 c1 00 00 06 00 14 2a 02 c6 a0 40 15 00 11 00 00 00 00 00 00 00 83 00 05 00 08 d4 c9 79 53 00 07 01 80 4b 41 4d 45 2d 42 53 44 20 31 2e 31 00 00 00 00 64 11 49 00 00 00 00 00 ac de 0c 00 00 00 00 00 60 ea 00 00 00 00 00 00 00 00 00 00 b2 d4 38 45 c7 a1 b0 4d d4 c9 79 52 00 00 00 00 00 00 00 00 00 00 00 00 05 00 00 00 d4 c9 79 53 00 00 00 00 00 00 00 00 00 00 00 00 05 00 00 00 00 00 00 00 d9 05 13 89 01 01 00 00 00 00 00 00 00 00 00 00 01 00 00 80 45 38 d4 b2 00 1c 71 c7 00 01 ff ff ac 40 9b 94 80 00 00 04 c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 c8 24 46 8c 7e 88 2e b7 88 8b dd a1 55 8b b4 c0 26 e3 21 bb b0 66 fd b2 d4 de f9 77 4f e4 7c bf 80 04 00 08 00 03 00 01 80 03 00 07 00 80 c1 00 00 0c 00 08 00 05 00 06 00 06 00 14 2a 02 c6 a0 40 15 00 11 00 00 00 00 00 00 00 82 00 05 00 08 d4 c9 79 52 02 00 01 f8 c7 a1 b0 4d 00 1c 71 c7 00 01 ff ff 03 91 94 1b 80 00 00 04 c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 61 6c 7e 52 2a db e0 a2 aa 78 25 1e 12 c5 01 9e 4c 60 16 df 01 6d a1 d5 cd be a7 5d a2 73 f4 1b 80 04 00 08 00 03 00 01 80 03 00 07 00 80 c1 00 00 06 00 14 2a 02 c6 a0 40 15 00 11 00 00 00 00 00 00 00 83 00 05 00 08 d4 c9 79 53 64 30 8a b9 7c e5 93 69 52 a9 c8 d5 a1 1b 7d ef ea fa 23 32 # SCTP_PACKET
[0.006] Ok, Common input processing called, m:0x611000000900 iphlen:0 offset:12 length:516 stcb:0x61d000001480
[0.006] stcb:0x61d000001480 state:2
[0.006] sctp_process_control: iphlen=0, offset=12, length=516 stcb:0x61d000001480
[0.006] sctp_process_control: processing a chunk type=2, len=504
[0.006] SCTP_INIT_ACK
[0.006] sctp_handle_init_ack: handling INIT-ACK
[0.006] Check for unrecognized param's
[0.006] Hit default param 8004
[0.006] move on
[0.007] SCTP: add HMAC id 1 to list
[0.007] SCTP: added chunk 0 (0x00) to Auth list
[0.007] SCTP: added chunk 128 (0x80) to Auth list
[0.007] SCTP: added chunk 193 (0xc1) to Auth list
[0.007] SCTP: negotiated peer HMAC id 1
[0.007] moving to COOKIE-ECHOED state
[0.007] Leaving handle-init-ack end

O 13:50:37.287790 0000 13 88 13 89 c7 a1 b0 4d 00 00 00 00 0a 00 01 80 4b 41 4d 45 2d 42 53 44 20 31 2e 31 00 00 00 00 64 11 49 00 00 00 00 00 ac de 0c 00 00 00 00 00 60 ea 00 00 00 00 00 00 00 00 00 00 b2 d4 38 45 c7 a1 b0 4d d4 c9 79 52 00 00 00 00 00 00 00 00 00 00 00 00 05 00 00 00 d4 c9 79 53 00 00 00 00 00 00 00 00 00 00 00 00 05 00 00 00 00 00 00 00 d9 05 13 89 01 01 00 00 00 00 00 00 00 00 00 00 01 00 00 80 45 38 d4 b2 00 1c 71 c7 00 01 ff ff ac 40 9b 94 80 00 00 04 c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 c8 24 46 8c 7e 88 2e b7 88 8b dd a1 55 8b b4 c0 26 e3 21 bb b0 66 fd b2 d4 de f9 77 4f e4 7c bf 80 04 00 08 00 03 00 01 80 03 00 07 00 80 c1 00 00 0c 00 08 00 05 00 06 00 06 00 14 2a 02 c6 a0 40 15 00 11 00 00 00 00 00 00 00 82 00 05 00 08 d4 c9 79 52 02 00 01 f8 c7 a1 b0 4d 00 1c 71 c7 00 01 ff ff 03 91 94 1b 80 00 00 04 c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 61 6c 7e 52 2a db e0 a2 aa 78 25 1e 12 c5 01 9e 4c 60 16 df 01 6d a1 d5 cd be a7 5d a2 73 f4 1b 80 04 00 08 00 03 00 01 80 03 00 07 00 80 c1 00 00 06 00 14 2a 02 c6 a0 40 15 00 11 00 00 00 00 00 00 00 83 00 05 00 08 d4 c9 79 53 64 30 8a b9 7c e5 93 69 52 a9 c8 d5 a1 1b 7d ef ea fa 23 32 # SCTP_PACKET
[0.007] m-c-o put out 0
[0.007] Ok, we have put out 0 chunks
[0.007] Check for chunk output prw:1864135 tqe:0 tf=0
[0.007] Calling chunk OUTPUT
[0.007] m-c-o put out 0
[0.007] Ok, we have put out 0 chunks
[0.007] chunk OUTPUT returns
[0.007]  >>> Injecting INIT_ACK

I 13:50:37.288156 0000 13 89 13 88 05 4c 2b 95 00 00 00 00 0b 00 00 04 # SCTP_PACKET
[0.007] Ok, Common input processing called, m:0x6110000016c0 iphlen:0 offset:12 length:16 stcb:0x61d000001480
[0.007] stcb:0x61d000001480 state:4
[0.007] sctp_process_control: iphlen=0, offset=12, length=16 stcb:0x61d000001480
[0.008] sctp_process_control: processing a chunk type=11, len=4
[0.008] SCTP_COOKIE_ACK, stcb 0x61d000001480
[0.008] sctp_handle_cookie_ack: handling COOKIE-ACK
[0.008] moving to OPEN state
[0.008] Check for chunk output prw:1864135 tqe:1 tf=0
[0.008] handle_upcall() called - implement logic!
[0.008]  >>> Injecting COOKIE_ACK
[0.008] Send called addr:0x0 send length 41
[0.008] sctp_auth_key_acquire: stcb 0x61d000001480 key 0 refcount acquire to 2
[0.008] sctp_auth_key_acquire: stcb 0x61d000001480 key 0 refcount acquire to 3
[0.009] caching key id 0
[0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] [0.009] Assoc Key: len 99, 8002002408c280d52d1df40954ed5a539dfef97295e8b144e5ad8d003b65a03b5b1d48cd8003000680c180040006000180020024616c7e522adbe0a2aa78251e12c5019e4c6016df016da1d5cdbea75da273f41b800300070080c18004000800030001

O 13:50:37.289938 0000 13 88 13 89 c7 a1 b0 4d 00 00 00 00 0f 00 00 1c 00 00 00 01 3a 61 bc e8 d9 fd 26 7c 8a 36 88 f5 03 84 56 ac 50 ad db 5d 00 02 00 39 3c db 41 bc 00 00 00 00 00 00 00 00 47 65 6f 6c 6f 67 69 65 20 69 73 74 20 6b 65 69 6e 65 20 72 69 63 68 74 69 67 65 20 57 69 73 73 65 6e 73 63 68 61 66 74 21 00 00 00 # SCTP_PACKET
[0.009] m-c-o put out 1
[0.009] Ok, we have put out 1 chunks
[0.009] USR Send complete qo:0 prw:1863819 unsent:41 tf:57 cooq:1 toqs:57 err:0

I 13:50:37.290147 0000 13 89 13 88 05 4c 2b 95 00 00 00 00 03 16 00 10 96 01 00 00 ad 01 ff c5 02 1c 6c d7 04 00 00 09 ff 1c 1c ff ff ff 00 00 04 01 00 07 00 04 0c 0c 04 00 00 2c 00 01 00 28 31 01 00 14 ac de 0c 00 d1 4b 07 e1 7d c5 04 b7 ad f9 fe c5 02 1c 6c d7 04 00 00 09 ff 1c 1c ff ff ff 00 00 05 00 00 2c 00 01 00 28 18 00 26 86 b5 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 10 01 00 01 00 00 00 00 00 00 00 ad 01 ff c5 02 1c 6c d7 04 00 00 09 ff 1c 1c ff ff ff 00 00 04 01 00 07 00 04 0c 0c 04 00 00 2c 00 01 00 28 32 01 00 14 ac de 0c 00 d1 4b 07 e1 7d c5 04 b7 ad f9 5c ff ff ff ff 81 fe 02 e3 09 ff 1c 1c ff ff ff 00 00 05 00 00 2c 00 01 00 28 18 00 be 86 b5 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 10 01 00 01 00 00 00 00 00 00 00 03 00 00 10 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 10 01 00 01 d7 04 00 00 09 ff 1c 1c ff ff ff 00 00 05 00 02 6f 01 00 61 d0 02 02 5e 78 6c d7 04 00 00 09 ff 1c 1c ff ff ff 0c 0c 04 49 00 00 00 ac de 0c 00 00 # SCTP_PACKET
[0.010] Ok, Common input processing called, m:0x611000001f80 iphlen:0 offset:12 length:303 stcb:0x61d000001480
[0.010] stcb:0x61d000001480 state:8
[0.010] sctp_process_control: iphlen=0, offset=12, length=303 stcb:0x61d000001480
[0.010] sctp_process_control: processing a chunk type=3, len=16
[0.010] SCTP_SACK
[0.010] Bad size of SACK chunk
[0.010] sctp_process_control: processing a chunk type=4, len=9
[0.010] SCTP_HEARTBEAT
[0.010] sctp_process_control: processing a chunk type=4, len=7
[0.010] SCTP_HEARTBEAT
[0.010] sctp_process_control: processing a chunk type=4, len=44
[0.010] SCTP_HEARTBEAT
[0.010] sctp_process_control: processing a chunk type=5, len=44
[0.010] SCTP_HEARTBEAT_ACK
[0.010] sctp_process_control: processing a chunk type=4, len=9
[0.010] SCTP_HEARTBEAT
[0.010] sctp_process_control: processing a chunk type=4, len=7
[0.010] SCTP_HEARTBEAT
[0.010] sctp_process_control: processing a chunk type=4, len=44
[0.010] SCTP_HEARTBEAT
[0.010] sctp_process_control: processing a chunk type=5, len=44
[0.010] SCTP_HEARTBEAT_ACK
/Users/weinrank/temp/usrsctp/usrsctplib/netinet/sctputil.c:2653:15: runtime error: signed integer overflow: 1955827320 + 723124158 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/weinrank/temp/usrsctp/usrsctplib/netinet/sctputil.c:2653:15 in
==67137== ERROR: libFuzzer: deadly signal
    #0 0x10bde3ab7 in __sanitizer_print_stack_trace (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x6aab7)
    #1 0x10a70b2a8 in fuzzer::PrintStackTrace() FuzzerUtil.cpp:206
    #2 0x10a6eaa18 in fuzzer::Fuzzer::CrashCallback() FuzzerLoop.cpp:237
    #3 0x10a6ea9df in fuzzer::Fuzzer::StaticCrashSignalCallback() FuzzerLoop.cpp:209
    #4 0x7fff75bdab5c in _sigtramp (libsystem_platform.dylib:x86_64+0x4b5c)
    #5 0x113c59b75 in dyld::fastBindLazySymbol(ImageLoader**, unsigned long) (dyld:x86_64+0x4b75)
    #6 0x7fff75a946a5 in abort (libsystem_c.dylib:x86_64+0x5b6a5)
    #7 0x10bdfa505 in __sanitizer::Abort() (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x81505)
    #8 0x10bdf9e83 in __sanitizer::Die() (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x80e83)
    #9 0x10be087ae in __ubsan_handle_add_overflow_abort (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x8f7ae)
    #10 0x10a4ea6a5 in sctp_calculate_rto sctputil.c:2653
    #11 0x109ca9cf9 in sctp_handle_heartbeat_ack sctp_input.c:724
    #12 0x109c89675 in sctp_process_control sctp_input.c:5233
    #13 0x109c63f05 in sctp_common_input_processing sctp_input.c:5898
    #14 0x10a6ca739 in usrsctp_conninput user_socket.c:3518
    #15 0x1099a3e3d in LLVMFuzzerTestOneInput fuzzer_connect.c:438
    #16 0x10a6ebdd8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) FuzzerLoop.cpp:533
    #17 0x10a6df651 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) FuzzerDriver.cpp:280
    #18 0x10a6e44cb in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) FuzzerDriver.cpp:709
    #19 0x10a70c592 in main FuzzerMain.cpp:20
    #20 0x7fff759ef3d4 in start (libdyld.dylib:x86_64+0x163d4)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
```
PCAP: 
[rtt.pcapng.zip](https://github.com/sctplab/usrsctp/files/3626216/rtt.pcapng.zip)

# Reproduce
```
git clone https://github.com/weinrank/usrsctp --branch fuzzer-connected --single-branch
cd usrsctp
./build-fuzzer.sh
cd fuzzer
./fuzzer_connect_multi ./CORPUS_CONNECT/crash-0a63175dc6b51474dc08197431ec36d11db5e77b
```

**Comment by tuexen** [comment]
@weinrank I think https://github.com/sctplab/usrsctp/commit/b7ed78b2faebd97ef57791c99156c3e0d600a8a2 fixes this issue. Can you retest and report?

**Comment by weinrank** [comment]
Fixed!
