### ISSUE TITLE
NULL deref crash in sctp_timer_start when processing fuzzed ASCONF

### ISSUE THREAD

**Issue by markwo** [sctplab/usrsctp#380]
Hit this issue when fuzzing ASCONF chunks. A PCAP is attached.
The crash occurs when sctp_timer_start() is called here: https://github.com/sctplab/usrsctp/blob/ac364403c13c5cefe2bc5e87b8bf730ba7d491a0/usrsctplib/netinet/sctp_asconf.c#L268
[repro.pcap.zip](https://github.com/sctplab/usrsctp/files/3654125/repro.pcap.zip)

```
usrsctp: sctp_process_control: processing a chunk type=193, len=40
usrsctp: SCTP_ASCONF
usrsctp: handle_asconf: serial number = b5ed35a2h (expected next = b5ed35a2h)
usrsctp: handle_asconf: asconf_limit=80, sequence=b5ed35a2h
usrsctp: handle_asconf: Now processing first ASCONF. Try to delete old cache
usrsctp: process_asconf_add_ip: adding 
usrsctp: IPv4 address: 0.0.0.0:5000
usrsctp: process_asconf_add_ip: using source addr 
usrsctp: AF_CONN address: 0x60c000000280
usrsctp: Adding an address (from:6) to the peer: 
usrsctp: AF_CONN address: 0x60c000000280

AddressSanitizer:DEADLYSIGNAL
=================================================================
==224135==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000025d (pc 0x55e65eaec0f8 bp 0x7ffd0dda18d0 sp 0x7ffd0dda1880 T0)
==224135==The signal is caused by a READ memory access.
==224135==Hint: address points to the zero page.
usrsctp: Timer type 17 goes off

usrsctp: Timer now complete (type = 17)

    #0 0x55e65eaec0f7 in sctp_timer_start third_party/usrsctp/usrsctplib/netinet/sctputil.c:2257:12
    #1 0x55e65eb13566 in sctp_process_asconf_add_ip third_party/usrsctp/usrsctplib/netinet/sctp_asconf.c:268:3
    #2 0x55e65eb11502 in sctp_handle_asconf third_party/usrsctp/usrsctplib/netinet/sctp_asconf.c:742:15
    #3 0x55e65eab9e09 in sctp_process_control third_party/usrsctp/usrsctplib/netinet/sctp_input.c:5492:5
    #4 0x55e65eae1865 in sctp_common_input_processing third_party/usrsctp/usrsctplib/netinet/sctp_input.c:5899:10
    #5 0x55e65ea717e7 in usrsctp_conninput third_party/usrsctp/usrsctplib/user_socket.c:3518:2
    <snip>

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV third_party/usrsctp/usrsctplib/netinet/sctputil.c:2257:12 in sctp_timer_start
==224135==ABORTING
```

**Comment by tuexen** [comment]
Is it possible to share with @weinrank some information such that @weinrank can run a reproducer locally in our lab?

**Comment by markwo** [comment]
Sure, I will send the info tomorrow.

**Comment by markwo** [comment]
I added a stand-alone repro program in this branch:
https://github.com/markwo/usrsctp/tree/fuzzer_repro

Since the issue is due to an uninitialized pointer on the stack,  the crash doesn't always trigger (sctp_timer_start checks for NULL inputs). The best way to catch this is with -fsanitize=memory. I was building the project as follows:
`cmake -DCMAKE_C_COMPILER=/usr/bin/clang-8 -Dsctp_build_repro=1 -Dsctp_sanitizer_memory=1 -Dsctp_sanitizer_address=0 -Dsctp_debug=1 .`

Then run repro/repro_380. Output:
```
[S][0.000] vrf_id 0x0: adding address: [S][0.000] AF_CONN address: 0x1
[P][0.000] usrsctp initialized
[S][0.002] SCTP: add HMAC id 1 to list
[S][0.002] SCTP: added chunk 193 (0xc1) to Auth list
[S][0.002] SCTP: added chunk 128 (0x80) to Auth list
[S][0.002] Bind called port: 5000
[S][0.002] Addr: [S][0.002] IPv4 address: 0.0.0.0:5000
[S][0.002] Main hash to bind at head:0x724000000098, bound port:5000 - in tcp_pool=0
[P][0.002] Calling usrsctp_connect()
[S][0.002] Allocate an association for peer:[S][0.002] AF_CONN address: 0x1
[S][0.002] Port:5001
[S][0.002] Adding an address (from:1) to the peer: [S][0.002] AF_CONN address: 0x1
[S][0.003] Association 0x71d000000000 now allocated
[S][0.003] Sending INIT
[S][0.003] Sending INIT - calls lowlevel_output
[P][0.003] Found outgoing INIT, extracting VTAG : 3131831035

O 15:27:38.195430 0000 13 88 13 89 00 00 00 00 00 00 00 00 01 00 00 5a fb f2 ab ba 00 02 00 00 00 0a 08 00 00 00 00 f8 80 00 00 04 c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 80 04 00 06 00 01 00 00 80 03 00 06 80 c1 00 00 # SCTP_PACKET
[P][0.004] Injecting INIT

I 15:27:38.195867 0000 13 89 13 88 00 00 00 00 00 00 00 00 01 00 00 50 01 00 00 00 00 00 20 00 00 08 00 08 00 00 00 01 80 08 00 07 c1 80 0f 00 80 03 00 07 00 c1 80 00 80 02 00 24 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 80 04 00 07 00 01 00 00 # SCTP_PACKET
[S][0.004] stcb:0x71d000000000 inp:0x719000000000
[S][0.004] stcb is 0x71d000000000
[S][0.004] Ok, Common input processing called, m:0x710000010100 iphlen:0 offset:12 length:92 stcb:0x71d000000000
[S][0.004] stcb:0x71d000000000 state:2
[S][0.004] sctp_process_control: iphlen=0, offset=12, length=92 stcb:0x71d000000000
[S][0.004] Its an INIT of len:80 vtag:0
[S][0.004] sctp_process_control: processing a chunk type=1, len=80
[S][0.004] SCTP_INIT
[S][0.004] sctp_handle_init: handling INIT tcb:0x71d000000000
[S][0.004] sctp_handle_init: sending INIT-ACK
[S][0.004] Check for unrecognized param's
[S][0.004] Hit default param 8004
[S][0.004] move on

O 15:27:38.196549 0000 13 88 13 89 01 00 00 00 00 00 00 00 02 00 01 90 fb f2 ab ba 00 02 00 00 00 08 08 00 00 00 00 f8 80 00 00 04 c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 80 04 00 06 00 01 00 00 80 03 00 06 80 c1 00 00 00 07 01 34 4b 41 4d 45 2d 42 53 44 20 31 2e 31 00 00 00 00 5a 3b 8d 5d 00 00 00 00 f3 fd 02 00 00 00 00 00 60 ea 00 00 e3 00 00 00 46 7c c2 54 00 00 00 01 fb f2 ab ba 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 13 89 13 88 00 00 01 00 01 01 01 00 00 00 00 00 01 00 00 50 01 00 00 00 00 00 20 00 00 08 00 08 00 00 00 01 80 08 00 07 c1 80 0f 00 80 03 00 07 00 c1 80 00 80 02 00 24 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 80 04 00 07 00 01 00 00 02 00 01 90 fb f2 ab ba 00 02 00 00 00 08 08 00 00 00 00 f8 80 00 00 04 c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 80 04 00 06 00 01 00 00 80 03 00 06 80 c1 00 00 b4 82 2a fd b8 68 b3 4b b9 91 4d ad 29 b9 a4 60 61 a3 76 e0 # SCTP_PACKET
[P][0.005] Injecting 2nd packet

I 15:27:38.196602 0000 13 89 13 88 fb f2 ab ba 00 00 00 00 0f 00 00 1c 00 00 00 01 aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa c1 0c 00 28 ff ff 9a c1 53 ff 00 08 ff 0c 53 1c c0 01 00 0e 00 00 fe ff 00 05 00 08 00 00 00 00 5d 8b 2c bd ff 04 fc ff # SCTP_PACKET
[S][0.005] Ok, Common input processing called, m:0x710000010200 iphlen:0 offset:12 length:80 stcb:0x71d000000000
[S][0.005] stcb:0x71d000000000 state:2
[S][0.005] sctp_process_control: iphlen=0, offset=12, length=80 stcb:0x71d000000000
[S][0.005] sctp_process_control: processing a chunk type=15, len=28
[S][0.005] SCTP_AUTHENTICATION
[S][0.005] SCTP AUTH Chunk: shared key 0, HMAC id 1
[S][0.005] Recv Key: len 48, [S][0.005] 80[S][0.005] 02[S][0.005] 00[S][0.005] 24[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 41[S][0.005] 80[S][0.005] 03[S][0.005] 00[S][0.005] 06[S][0.005] 80[S][0.005] c1[S][0.005] 80[S][0.005] 04[S][0.005] 00[S][0.005] 06[S][0.005] 00[S][0.005] 01[S][0.005] 
[S][0.005] sctp_process_control: processing a chunk type=193, len=40
[S][0.005] SCTP_ASCONF
[S][0.005] handle_asconf: asconf_limit=80, sequence=f8h
[S][0.005] handle_asconf: Now processing first ASCONF. Try to delete old cache
[S][0.005] process_asconf_add_ip: adding [S][0.005] IPv4 address: 0.0.0.0:5001
[S][0.005] process_asconf_add_ip: using source addr [S][0.005] AF_CONN address: 0x1
[S][0.005] Adding an address (from:6) to the peer: [S][0.005] AF_CONN address: 0x1
==212212==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0xa194d3 in sctp_timer_start (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0xa194d3)
    #1 0xb23167 in sctp_process_asconf_add_ip (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0xb23167)
    #2 0xb1c227 in sctp_handle_asconf (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0xb1c227)
    #3 0x554a23 in sctp_process_control (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0x554a23)
    #4 0x53191a in sctp_common_input_processing (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0x53191a)
    #5 0x5014e0 in usrsctp_conninput (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0x5014e0)
    #6 0x4aca05 in main /usr/local/google/home/markwo/repos/usrsctp/repro/repro_380.c:184:3
    #7 0x7f145e53e52a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2352a)
    #8 0x42a439 in _start (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0x42a439)

  Uninitialized value was stored to memory at
    #0 0xa15115 in sctp_timer_start (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0xa15115)
    #1 0xb23167 in sctp_process_asconf_add_ip (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0xb23167)
    #2 0xb1c227 in sctp_handle_asconf (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0xb1c227)
    #3 0x554a23 in sctp_process_control (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0x554a23)
    #4 0x53191a in sctp_common_input_processing (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0x53191a)
    #5 0x5014e0 in usrsctp_conninput (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0x5014e0)
    #6 0x4aca05 in main /usr/local/google/home/markwo/repos/usrsctp/repro/repro_380.c:184:3
    #7 0x7f145e53e52a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2352a)

  Uninitialized value was created by an allocation of 'net' in the stack frame of function 'sctp_process_asconf_add_ip'
    #0 0xb1f080 in sctp_process_asconf_add_ip (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0xb1f080)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_380+0xa194d3) in sctp_timer_start
```

**Comment by tuexen** [comment]
@markwo Please retest and report.

**Comment by markwo** [comment]
Tested the fix - looks good.
