### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow (read of size 2) in sctp_process_asconf_add_ip

### ISSUE THREAD

**Issue by markwo** [sctplab/usrsctp#386]
Repro program output:
```
[S][0.000] vrf_id 0x0: adding address: [S][0.000] AF_CONN address: 0x1
[P][0.000] usrsctp initialized
[S][0.000] SCTP: add HMAC id 1 to list
[S][0.000] SCTP: added chunk 193 (0xc1) to Auth list
[S][0.000] SCTP: added chunk 128 (0x80) to Auth list
[S][0.000] Bind called port: 5000
[S][0.000] Addr: [S][0.000] IPv4 address: 0.0.0.0:5000
[S][0.000] Main hash to bind at head:0x625000000198, bound port:5000 - in tcp_pool=0
[P][0.000] Calling usrsctp_connect()
[S][0.000] Allocate an association for peer:[S][0.000] AF_CONN address: 0x1
[S][0.000] Port:5001
[S][0.000] Adding an address (from:1) to the peer: [S][0.000] AF_CONN address: 0x1
[S][0.000] Association 0x61d000001480 now allocated
[S][0.000] Sending INIT
[S][0.000] Sending INIT - calls lowlevel_output
[P][0.000] Found outgoing INIT, extracting VTAG : 3131831035

O 15:51:30.801700 0000 13 88 13 89 00 00 00 00 00 00 00 00 01 00 00 5a fb f2 ab ba 00 02 00 00 00 0a 08 00 00 00 00 f8 80 00 00 04 c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 80 04 00 06 00 01 00 00 80 03 00 06 80 c1 00 00 # SCTP_PACKET
[P][0.000] Injecting INIT

I 15:51:30.801824 0000 13 89 13 88 00 00 00 00 00 00 00 00 01 00 00 50 01 00 00 00 00 00 20 00 00 08 00 08 00 00 00 01 80 08 00 07 c1 80 0f 00 80 03 00 07 00 c1 80 00 80 02 00 24 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 80 04 00 07 00 01 00 00 # SCTP_PACKET
[S][0.000] stcb:0x61d000001480 inp:0x619000000080
[S][0.000] stcb is 0x61d000001480
[S][0.000] Ok, Common input processing called, m:0x61100001a300 iphlen:0 offset:12 length:92 stcb:0x61d000001480
[S][0.000] stcb:0x61d000001480 state:2
[S][0.000] sctp_process_control: iphlen=0, offset=12, length=92 stcb:0x61d000001480
[S][0.000] Its an INIT of len:80 vtag:0
[S][0.000] sctp_process_control: processing a chunk type=1, len=80
[S][0.000] SCTP_INIT
[S][0.000] sctp_handle_init: handling INIT tcb:0x61d000001480
[S][0.000] sctp_handle_init: sending INIT-ACK
[S][0.000] Check for unrecognized param's
[S][0.000] Hit default param 8004
[S][0.000] move on

O 15:51:30.802227 0000 13 88 13 89 01 00 00 00 00 00 00 00 02 00 01 90 fb f2 ab ba 00 02 00 00 00 08 08 00 00 00 00 f8 80 00 00 04 c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 80 04 00 06 00 01 00 00 80 03 00 06 80 c1 00 00 00 07 01 34 4b 41 4d 45 2d 42 53 44 20 31 2e 31 00 00 00 00 f2 40 8d 5d 00 00 00 00 cd 3c 0c 00 00 00 00 00 60 ea 00 00 e3 00 00 00 46 7c c2 54 00 00 00 01 fb f2 ab ba 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 13 89 13 88 00 00 01 00 01 01 01 00 00 00 00 00 01 00 00 50 01 00 00 00 00 00 20 00 00 08 00 08 00 00 00 01 80 08 00 07 c1 80 0f 00 80 03 00 07 00 c1 80 00 80 02 00 24 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 80 04 00 07 00 01 00 00 02 00 01 90 fb f2 ab ba 00 02 00 00 00 08 08 00 00 00 00 f8 80 00 00 04 c0 00 00 04 80 08 00 09 c0 0f c1 80 82 00 00 00 80 02 00 24 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 80 04 00 06 00 01 00 00 80 03 00 06 80 c1 00 00 65 81 df 60 62 4b fa 22 fd ab a6 d0 c4 58 4b 6e ce 14 84 61 # SCTP_PACKET
[P][0.001] Injecting 2nd packet

I 15:51:30.802289 0000 13 89 13 88 fb f2 ab ba 00 00 00 00 0f 00 00 1c 00 00 00 01 aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa c1 7f 00 d4 7d 01 00 0a 01 06 00 5d 8c 20 c0 01 00 06 00 5d 8c 20 c0 01 00 06 00 00 0a 10 01 01 00 0f c1 00 26 0a 21 3d 00 ff ff ff 01 00 0a 01 06 00 00 0a 10 8b c7 00 30 00 00 0a 41 06 f3 08 15 00 00 02 00 00 00 00 01 07 00 00 00 00 00 00 01 00 01 c1 7f 6b c8 7a 01 ff ff ff 01 00 0a 01 06 00 5d 8c 20 c0 01 00 06 00 00 0a 10 8b c7 00 30 00 00 0a 41 06 f3 08 15 00 00 02 00 00 00 00 01 07 00 00 f1 00 00 00 01 00 01 c1 7f 6b c8 7a 01 ff ff ff 01 00 0a 01 06 00 5d 8c 20 c0 01 00 06 00 5d 8c 20 c0 01 00 06 00 00 0a 10 01 01 00 0f c1 00 26 0a 21 3d 00 10 41 0a 00 00 01 00 00 00 00 01 00 0a 01 00 01 09 ff ff 40 d8 23 d8 00 03 11 01 00 00 00 00 # SCTP_PACKET
[S][0.001] Ok, Common input processing called, m:0x61100001ae40 iphlen:0 offset:12 length:255 stcb:0x61d000001480
[S][0.001] stcb:0x61d000001480 state:2
[S][0.001] sctp_process_control: iphlen=0, offset=12, length=255 stcb:0x61d000001480
[S][0.001] sctp_process_control: processing a chunk type=15, len=28
[S][0.001] SCTP_AUTHENTICATION
[S][0.001] SCTP AUTH Chunk: shared key 0, HMAC id 1
[S][0.001] Recv Key: len 48, [S][0.001] 80[S][0.001] 02[S][0.001] 00[S][0.001] 24[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 41[S][0.001] 80[S][0.001] 03[S][0.001] 00[S][0.001] 06[S][0.001] 80[S][0.001] c1[S][0.001] 80[S][0.001] 04[S][0.001] 00[S][0.001] 06[S][0.001] 00[S][0.001] 01[S][0.001] 
[S][0.001] sctp_process_control: processing a chunk type=193, len=212
[S][0.001] SCTP_ASCONF
[S][0.001] handle_asconf: asconf_limit=252, sequence=f8h
[S][0.001] handle_asconf: Now processing first ASCONF. Try to delete old cache
=================================================================
==217602==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61100001b1c0 at pc 0x000000d6b683 bp 0x7ffedf2a78d0 sp 0x7ffedf2a78c8
READ of size 2 at 0x61100001b1c0 thread T0
    #0 0xd6b682 in sctp_process_asconf_add_ip (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0xd6b682)
    #1 0xd675b1 in sctp_handle_asconf (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0xd675b1)
    #2 0x5d4f5b in sctp_process_control (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0x5d4f5b)
    #3 0x5b3779 in sctp_common_input_processing (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0x5b3779)
    #4 0x584508 in usrsctp_conninput (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0x584508)
    #5 0x536171 in main (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0x536171)
    #6 0x7fcfb09d452a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2352a)
    #7 0x4294c9 in _start (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0x4294c9)

0x61100001b1c0 is located 0 bytes to the right of 256-byte region [0x61100001b0c0,0x61100001b1c0)
allocated by thread T0 here:
    #0 0x4f37f7 in malloc (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0x4f37f7)
    #1 0xd0dc83 in m_get (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0xd0dc83)
    #2 0xd3c8d3 in m_copyback (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0xd3c8d3)
    #3 0x583ab0 in usrsctp_conninput (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0x583ab0)
    #4 0x536171 in main (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0x536171)
    #5 0x7fcfb09d452a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2352a)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/local/google/home/markwo/repos/usrsctp/repro/repro_new+0xd6b682) in sctp_process_asconf_add_ip
Shadow bytes around the buggy address:
  0x0c227fffb5e0: 00 00 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
  0x0c227fffb5f0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c227fffb600: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c227fffb610: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c227fffb620: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c227fffb630: 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa
  0x0c227fffb640: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fffb650: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fffb660: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c227fffb670: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fffb680: 00 00 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==217602==ABORTING
```

**Comment by markwo** [comment]
See https://github.com/markwo/usrsctp/tree/fuzzer_repro

To repro, build repro_386 with address sanitizer:
`cmake -DCMAKE_C_COMPILER=/usr/bin/clang-8 -Dsctp_build_repro=1 -Dsctp_sanitizer_memory=0 -Dsctp_sanitizer_address=1 -Dsctp_debug=1 .`

**Comment by weinrank** [comment]
Hi Mark,

our fuzzing system found the same issue on FreeBSD and Linux tonight. :)

**Comment by tuexen** [comment]
I fixed a some issues reported by OSS-Fuzz. I think the commit https://github.com/sctplab/usrsctp/commit/54f46950f494df7af9f61b617686ffa50a52815c fixes this issue. Can you retest and report?

**Comment by markwo** [comment]
Retested, and the fix above does address this issue. Closing.
