### ISSUE TITLE
ERROR: libFuzzer: deadly signal

### ISSUE THREAD

**Issue by weinrank** [sctplab/usrsctp#466]
### Log
```
Running: clusterfuzz-testcase-minimized-fuzzer_connect-5664878258028544
==52523== ERROR: libFuzzer: deadly signal
    #0 0x5383d1 in __sanitizer_print_stack_trace (/home/weinrank/Github/usrsctp/fuzzer/fuzzer_connect_multi+0x5383d1)
    #1 0x482a08 in fuzzer::PrintStackTrace() (/home/weinrank/Github/usrsctp/fuzzer/fuzzer_connect_multi+0x482a08)
    #2 0x468173 in fuzzer::Fuzzer::CrashCallback() (/home/weinrank/Github/usrsctp/fuzzer/fuzzer_connect_multi+0x468173)
    #3 0x7f98f44b13bf  (/lib/x86_64-linux-gnu/libpthread.so.0+0x153bf)
    #4 0x7f98f417318a in __libc_signal_restore_set /build/glibc-YYA7BZ/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h:86:3
    #5 0x7f98f417318a in raise /build/glibc-YYA7BZ/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:48:3
    #6 0x7f98f4152858 in abort /build/glibc-YYA7BZ/glibc-2.31/stdlib/abort.c:79:7
    #7 0x1171d09 in terminate_non_graceful /home/weinrank/Github/usrsctp/usrsctplib/user_environment.h:94:2
    #8 0x116ec79 in sctp_calc_rwnd /home/weinrank/Github/usrsctp/usrsctplib/netinet/sctp_indata.c:102:2
    #9 0x116d7f4 in sctp_set_rwnd /home/weinrank/Github/usrsctp/usrsctplib/netinet/sctp_indata.c:81:18
    #10 0x80ceb5 in sctp_send_sack /home/weinrank/Github/usrsctp/usrsctplib/netinet/sctp_output.c:11132:2
    #11 0x11870af in sctp_sack_check /home/weinrank/Github/usrsctp/usrsctplib/netinet/sctp_indata.c:2654:5
    #12 0x118fa8f in sctp_process_data /home/weinrank/Github/usrsctp/usrsctplib/netinet/sctp_indata.c:2955:2
    #13 0x61adc6 in sctp_common_input_processing /home/weinrank/Github/usrsctp/usrsctplib/netinet/sctp_input.c:6083:12
    #14 0x5dbe03 in usrsctp_conninput /home/weinrank/Github/usrsctp/usrsctplib/user_socket.c:3526:2
    #15 0x563128 in LLVMFuzzerTestOneInput /home/weinrank/Github/usrsctp/fuzzer/fuzzer_connect.c:430:2
    #16 0x469701 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/weinrank/Github/usrsctp/fuzzer/fuzzer_connect_multi+0x469701)
    #17 0x454021 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/weinrank/Github/usrsctp/fuzzer/fuzzer_connect_multi+0x454021)
    #18 0x459bee in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/weinrank/Github/usrsctp/fuzzer/fuzzer_connect_multi+0x459bee)
    #19 0x483132 in main (/home/weinrank/Github/usrsctp/fuzzer/fuzzer_connect_multi+0x483132)
    #20 0x7f98f41540b2 in __libc_start_main /build/glibc-YYA7BZ/glibc-2.31/csu/../csu/libc-start.c:308:16
    #21 0x42d58d in _start (/home/weinrank/Github/usrsctp/fuzzer/fuzzer_connect_multi+0x42d58d)
```

### Reproduce
```
./build_fuzzer.sh
./fuzzer_connect_multi clusterfuzz-testcase-minimized-fuzzer_connect-5664878258028544
```

[clusterfuzz-testcase-minimized-fuzzer_connect-5664878258028544.zip](https://github.com/sctplab/usrsctp/files/4621150/clusterfuzz-testcase-minimized-fuzzer_connect-5664878258028544.zip)

**Comment by tuexen** [comment]
Fixed in https://github.com/sctplab/usrsctp/commit/4f5d96284c23cb501eadf9aad2e76379ff1ead61.
