### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by shiretu** [sctplab/usrsctp#538]
Hi everyone,

I have a deadlock happening like this (relevant stack trace, the only 2 frames from sctp library):

1. [sctp_lower_sosend @ sctp_output.c:13738](https://github.com/sctplab/usrsctp/blob/a5ce87dd135f87f0110f649292bbdc51b7d8382a/usrsctplib/netinet/sctp_output.c#L13738)
1. [usrsctp_sendv @ user_socket.c:943 (discriminator 4)](https://github.com/sctplab/usrsctp/blob/a5ce87dd135f87f0110f649292bbdc51b7d8382a/usrsctplib/user_socket.c#L943)
1. (... app layers stack trace ...)

Further details:
1. Happens after continuously sending data for large periods of time. About once a day.
1. The git hash above is the exact hash we use in prod. We thought it would be great to upgrade to the latest version and try again. And so we did, upgrading to `995c0b84414466d77d52011e5b572cbe213b770a`. Unfortunately it behaved identically: after approximately 20-30 hours, it deadlocked.
1. I suspect a counter rolling over somewhere, ending up stimulating that code path in the wrong way. It is too clockwork... It always happens.

**Comment by tuexen** [comment]
Any chance to tell where the lock is held?

**Comment by shiretu** [comment]
@tuexen : sorry for the delay. No, we do not have that info unfortunately.

**Comment by paullouisageneau** [comment]
I think I'm witnessing a similar deadlock. Sadly the problem happens with a production build, therefore I don't have debug info in the backtraces.

`usrsctp_sendv` appears to be stuck at the same place:
```
Thread 1 (Thread 0x7f8f907f0780 (LWP 2555922)):
#0  __lll_lock_wait (futex=futex@entry=0x7f8e953eb618, private=0) at lowlevellock.c:52
#1  0x00007f8f909f30a3 in __GI___pthread_mutex_lock (mutex=0x7f8e953eb618) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007f8f707b3388 in sctp_lower_sosend ()
#3  0x00007f8f70792c59 in usrsctp_sendv ()
[...]
```
It seems to wait for `SCTP_TCB_LOCK` while holding `SCTP_INP_RLOCK`.

It appears `SCTP_TCB_LOCK` is held by the SCTP timer thread which itself waits for `SCTP_TCB_SEND_LOCK` in `sctp_is_there_unsent_data`. I couldn't find a running thread holding `SCTP_TCB_SEND_LOCK`.
```
Thread 17 (Thread 0x7f8f6d509700 (LWP 2555962)):
#0  __lll_lock_wait (futex=futex@entry=0x7f8e953eb640, private=0) at lowlevellock.c:52
#1  0x00007f8f909f30a3 in __GI___pthread_mutex_lock (mutex=0x7f8e953eb640) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007f8f7079ab3c in sctp_is_there_unsent_data ()
#3  0x00007f8f707b01f0 in sctp_med_chunk_output ()
#4  0x00007f8f707b2634 in sctp_chunk_output ()
#5  0x00007f8f707c6f70 in sctp_heartbeat_timer ()
#6  0x00007f8f707df53a in sctp_timeout_handler ()
#7  0x00007f8f70795ebb in sctp_handle_tick ()
#8  0x00007f8f70795fb3 in user_sctp_timer_iterate ()
#9  0x00007f8f909f0609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x00007f8f90917293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
This is a big issue as it freezes all SCTP connections: Thread 1 blocks another SCTP connection when it waits for `SCTP_INP_RLOCK` in `sctp_findassoc_by_vtag` (`RLOCK` and `WLOCK` both exclusively lock the mutex under the hood) while holding `SCTP_INP_INFO_RLOCK`:
```
Thread 221 (Thread 0x7f8e19441700 (LWP 2557489)):
#0  __lll_lock_wait (futex=futex@entry=0x7f8e953d9ef8, private=0) at lowlevellock.c:52
#1  0x00007f8f909f30a3 in __GI___pthread_mutex_lock (mutex=0x7f8e953d9ef8) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007f8f707bc141 in sctp_findassoc_by_vtag.constprop ()
#3  0x00007f8f707bc625 in sctp_findassociation_addr ()
#4  0x00007f8f707a03e9 in sctp_common_input_processing ()
#5  0x00007f8f70793f89 in usrsctp_conninput ()
[...]
```
Then all the other SCTP connections of the program get stuck waiting for `SCTP_INP_INFO_RLOCK` in `sctp_findassoc_by_vtag`:
```
Thread 56 (Thread 0x7f8ea4ff9700 (LWP 2556005)):
#0  __lll_lock_wait (futex=futex@entry=0x7f8f70c24d50 <system_base_info+176>, private=0) at lowlevellock.c:52
#1  0x00007f8f909f30a3 in __GI___pthread_mutex_lock (mutex=0x7f8f70c24d50 <system_base_info+176>) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007f8f707bc073 in sctp_findassoc_by_vtag.constprop () from /home/ubuntu/network-monorepo/packages/network/node_modules/node--Type <RET> for more, q to quit, c to continue without paging--
-datachannel/build/Release/node_datachannel.node
#3  0x00007f8f707bc625 in sctp_findassociation_addr ()
#4  0x00007f8f707a03e9 in sctp_common_input_processing ()
#5  0x00007f8f70793f89 in usrsctp_conninput ()
[...]
```
@tuexen Do you know what could cause `tcb_send_mtx` to be locked in the first place?

@shiretu Did you manage to investigate further on your side?

**Comment by tuexen** [comment]
I'm working on a locking cleanup which removes the TCB send lock. I hope that this hits the tree later this week. See https://github.com/sctplab/stream-reset-improved/tree/remove-stcb-send-lock This might not even compile yet...

**Comment by paullouisageneau** [comment]
> No, it should be changed. It is a rw lock in FreeBSD. Not sure why it is not that way in the userland stack. This came already up in a recent discussion about performance and scalability. I plan to change it.

I attempted to do the change in https://github.com/sctplab/usrsctp/pull/639
