### ISSUE TITLE
Segfault in "sctp_find_alternate_net" (timer thread)

### ISSUE THREAD

**Issue by cukiernick** [sctplab/usrsctp#555]
Hi,
Another segfault, this time in timer thread

usrsctp: `a17109528c75d01f6372d5c30851a639684c6e99`

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055d5bb68bf42 in sctp_find_alternate_net (stcb=0x7f46880dcdc0, net=0x7f46880e7b40, mode=0)
    at /home/user/cpp/usrsctp_lib-cpp/src/usrsctp_lib/usrsctplib/netinet/sctp_timer.c:350
350                     if (alt->ro.ro_rt == NULL) {
[Current thread is 1 (Thread 0x7f46a4e77700 (LWP 5349))]

(gdb) bt full
#0  0x000055d5bb68bf42 in sctp_find_alternate_net (stcb=0x7f46880dcdc0, net=0x7f46880e7b40, mode=0) at /home/user/cpp/usrsctp_lib-cpp/src/usrsctp_lib/usrsctplib/netinet/sctp_timer.c:350
        alt = 0x362d746e65696c63
        mnet = 0x7f46880e5ce0
        min_errors_net = 0x0
        max_cwnd_net = 0x0
        once = 0
        min_errors = -1
        max_cwnd = 0
#1  0x000055d5bb68da55 in sctp_t3rxt_timer (inp=0x7f4688083a30, stcb=0x7f46880dcdc0, net=0x7f46880e7b40) at /home/user/cpp/usrsctp_lib-cpp/src/usrsctp_lib/usrsctplib/netinet/sctp_timer.c:906
        alt = 0x0
        win_probe = 0
        num_mk = 21973
        num_abandoned = -1139085240
#2  0x000055d5bb6a8e1d in sctp_timeout_handler (t=0x7f46880e7c70) at /home/user/cpp/usrsctp_lib-cpp/src/usrsctp_lib/usrsctplib/netinet/sctputil.c:1893
        tv = {tv_sec = 0, tv_usec = 0}
        inp = 0x7f4688083a30
        stcb = 0x7f46880dcdc0
        net = 0x7f46880e7b40
        tmr = 0x7f46880e7c70
        op_err = 0x0
        upcall_socket = 0x55d5bc10fb80
        type = 1
        i = 0
        secret = 0
        did_output = true
        released_asoc_reference = true
#3  0x000055d5bb64b9dd in sctp_handle_tick (elapsed_ticks=10) at /home/user/cpp/usrsctp_lib-cpp/src/usrsctp_lib/usrsctplib/netinet/sctp_callout.c:172
        c = 0x7f46880e7c70
        c_func = 0x55d5bb6a8adc <sctp_timeout_handler>
        c_arg = 0x7f46880e7c70
#4  0x000055d5bb64baa7 in user_sctp_timer_iterate (arg=0x0) at /home/user/cpp/usrsctp_lib-cpp/src/usrsctp_lib/usrsctplib/netinet/sctp_callout.c:214
        amount = {tv_sec = 0, tv_nsec = 10000000}
        remaining = {tv_sec = 0, tv_nsec = 10000000}
#5  0x00007f46abdd2fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139941391070976, -1869884875519692240, 140732828235230, 140732828235231, 139941391070976, 0, 1765864404945334832, 1765835630796337712}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0,
              cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f46aae9d4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

(gdb) l -
335             for (;;) {
336                     alt = TAILQ_NEXT(mnet, sctp_next);
337                     if (alt == NULL) {
338                             once++;
339                             if (once > 1) {
340                                     break;
341                             }
342                             alt = TAILQ_FIRST(&stcb->asoc.nets);
343                             if (alt == NULL) {
344                                     return (NULL);
(gdb) l
345                             }
346                     }
347     #if defined(__FreeBSD__) && !defined(__Userspace__)
348                     if (alt->ro.ro_nh == NULL) {
349     #else
350                     if (alt->ro.ro_rt == NULL) {
351     #endif
352                             if (alt->ro._s_addr) {
353                                     sctp_free_ifa(alt->ro._s_addr);
354                                     alt->ro._s_addr = NULL;

(gdb) p alt
$1 = (struct sctp_nets *) 0x362d746e65696c63
(gdb) p *alt
Cannot access memory at address 0x362d746e65696c63
```

I think this may be related to 1st point in https://github.com/sctplab/usrsctp/issues/553 
Valgrind snip from mentioned issue:
```
Thread 7 SCTP timer:
Invalid read of size 8
   at 0x18E1B4: sctp_find_alternate_net (sctp_timer.c:350)
   by 0x18FCC6: sctp_t3rxt_timer (sctp_timer.c:906)
   by 0x1AB08E: sctp_timeout_handler (sctputil.c:1893)
   by 0x14DC4E: sctp_handle_tick (sctp_callout.c:172)
   by 0x14DD18: user_sctp_timer_iterate (sctp_callout.c:214)
   by 0x4863FA2: start_thread (pthread_create.c:486)
   by 0x55BE4CE: clone (clone.S:95)
 Address 0xad231e0 is 208 bytes inside a block of size 632 free'd
   at 0x48369AB: free (vg_replace_malloc.c:530)
   by 0x185E6B: sctp_remove_net (sctp_pcb.c:5193)
   by 0x185EEA: sctp_del_remote_addr (sctp_pcb.c:5227)
   by 0x1BDF64: sctp_process_asconf_delete_ip (sctp_asconf.c:437)
   by 0x1BEE39: sctp_handle_asconf (sctp_asconf.c:759)
   by 0x15B32B: sctp_process_control (sctp_input.c:5512)
   by 0x15C3AC: sctp_common_input_processing (sctp_input.c:5933)
   by 0x1BB230: recv_function_raw (user_recv_thread.c:427)
   by 0x4863FA2: start_thread (pthread_create.c:486)
   by 0x55BE4CE: clone (clone.S:95)
 Block was alloc'd at
   at 0x483577F: malloc (vg_replace_malloc.c:299)
   by 0x184161: sctp_add_remote_addr (sctp_pcb.c:4440)
   by 0x18A45E: sctp_load_addresses_from_init (sctp_pcb.c:7156)
   by 0x153825: sctp_process_cookie_new (sctp_input.c:2322)
   by 0x15483C: sctp_handle_cookie_echo (sctp_input.c:2888)
   by 0x15AE8D: sctp_process_control (sctp_input.c:5383)
   by 0x15C3AC: sctp_common_input_processing (sctp_input.c:5933)
   by 0x1BB230: recv_function_raw (user_recv_thread.c:427)
   by 0x4863FA2: start_thread (pthread_create.c:486)
   by 0x55BE4CE: clone (clone.S:95)
```

**Comment by tuexen** [comment]
I'm able to reproduce the use using a syzkaller reproducer found here: [Fatal trap 12: page fault in sctp_find_alternate_net](https://syzkaller.appspot.com/bug?id=4203a8b6db9149432fc53b9caab981832264b0ad).
